<a href="https://colab.research.google.com/github/Serarrs/dap-2024/blob/main/les03/rep.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<div align="center">

ФЕДЕРАЛЬНОЕ ГОСУДАРСТВЕННОЕ АВТОНОМНОЕ ОБРАЗОВАТЕЛЬНОЕ УЧРЕЖДЕНИЕ ВЫСШЕГО ОБРАЗОВАНИЯ
<br>
**«БЕЛГОРОДСКИЙ ГОСУДАРСТВЕННЫЙ НАЦИОНАЛЬНЫЙ
ИССЛЕДОВАТЕЛЬСКИЙ УНИВЕРСИТЕТ»
<br>
(НИУ «БелГУ»)**
<br><br>
ИНСТИТУТ ИНЖЕНЕРНЫХ И ЦИФРОВЫХ ТЕХНОЛОГИЙ
<br><br>
**Кафедра информационных и робототехнических систем**
<br><br><br><br>
**ОТЧЕТ**
<br>
по лабораторной работе №3
<br>
на тему: «NumPy»
<br>
по дисциплине
<br>
«Анализ данных на Python»
<br>
студента очной формы обучения
<br>
направления подготовки
<br><br><br>
09.03.02 – Информационные системы и технологии
<br>
3 курса группы 12002208
<br>
Кузьмина Анатолия Витальевича

<br><br><br><br><div>
<div align="right">

Проверил:
<br>
ДВОПУ
<br>
Чеботарев С. А.
<div><br><br><br>
<div align="center">

Белгород 2025
<div>
___________

<div align="center">

<br>Ход работы<br>

Задача №1. Создать массив 10x10 со случайными значениями, найти минимум и максимум (низкая)

In [6]:
import numpy as np
array = np.random.randint(0,101, size=(10, 10))
print("Массив 10x10:")
print(array)
min_value = np.min(array)
max_value = np.max(array)
print("\nМинимальное значение:", min_value)
print("Максимальное значение:", max_value)

Массив 10x10:
[[  7  52  87   8  65  65  48  14  46  98]
 [  3  66  31  62  99  72  95  76  26  89]
 [ 90  79  71  60  67  65  64  53  45  11]
 [ 90  18   3  54  69   2 100 100  53  30]
 [ 65  54  28  90  19  80  16  15  31  47]
 [ 24  86  41  53  97  93  13  64  53  37]
 [  0  32  86  80  95  51  80  57  65  91]
 [ 75   4  19  97   5  93  60  79  26  52]
 [ 35  53  93  82  81  56   5  92  73  72]
 [ 57  44  57  17  86  12  22  50  69  56]]

Минимальное значение: 0
Максимальное значение: 100


Задача №2. Создать 8x8 матрицу и заполнить её единицами и нулями в шахматном порядке

In [7]:
import numpy as np
chessboard = np.zeros((8, 8), dtype=int)
chessboard[1::2, ::2] = 1
chessboard[::2, 1::2] = 1
print(chessboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Задача №3. Дан массив из 11 элементов, поменять знак у элементов, значения которых между 3 и 8

In [8]:
import numpy as np
arr = np.random.randint(-10, 11, size=11)
print("Исходный массив:")
print(arr)
mask = (arr > 3) & (arr < 8)
arr[mask] = -arr[mask]
print("\nМассив после замены знака (для значений между 3 и 8):")
print(arr)

Исходный массив:
[ 7  0  7  8  1  7 -5 -6  4 -6 -1]

Массив после замены знака (для значений между 3 и 8):
[-7  0 -7  8  1 -7 -5 -6 -4 -6 -1]


Задача №4. Найти среднее заначение строки матрицы и вычесть его из каждого елемента строки

In [9]:
import numpy as np
matrix = np.random.randint(0, 11, size=(4, 5))
print("Исходная матрица:")
print(matrix)
row_means = matrix.mean(axis=1, keepdims=True)
result = matrix - row_means
print("\nРезультат (из каждого элемента строки вычтено среднее этой строки):")
print(result)

Исходная матрица:
[[ 5  8  2  2 10]
 [10  7 10 10 10]
 [ 4  1  9  5  8]
 [ 6 10  8  4  4]]

Результат (из каждого элемента строки вычтено среднее этой строки):
[[-0.4  2.6 -3.4 -3.4  4.6]
 [ 0.6 -2.4  0.6  0.6  0.6]
 [-1.4 -4.4  3.6 -0.4  2.6]
 [-0.4  3.6  1.6 -2.4 -2.4]]


Задача №5. Поменяйте 1 и 2 строки матрицы

In [10]:
import numpy as np
matrix = np.random.randint(0, 10, size=(4, 4))
print("Исходная матрица:")
print(matrix)
matrix[[0, 1]] = matrix[[1, 0]]

print("\nМатрица после обмена 1 и 2 строк:")
print(matrix)


Исходная матрица:
[[7 3 6 7]
 [1 7 8 2]
 [1 7 1 4]
 [0 0 6 8]]

Матрица после обмена 1 и 2 строк:
[[1 7 8 2]
 [7 3 6 7]
 [1 7 1 4]
 [0 0 6 8]]


Задача №6. Дан массив 10x2 подеставлющий собой точки в декартовой системе координат, преобразовать в полярную

In [11]:
import numpy as np
points = np.random.randint(-10, 11, size=(10, 2))
print("Декартовы координаты (x, y):")
print(points)
x = points[:, 0]
y = points[:, 1]

r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)
polar_points = np.column_stack((r, theta))

print("\nПолярные координаты (r, θ):")
print(polar_points)

Декартовы координаты (x, y):
[[  3  10]
 [  5  -1]
 [ -7 -10]
 [  0   9]
 [ -6   8]
 [ -5   7]
 [ -2  -3]
 [ -4   8]
 [ -1  -4]
 [ -3   1]]

Полярные координаты (r, θ):
[[10.44030651  1.27933953]
 [ 5.09901951 -0.19739556]
 [12.20655562 -2.18152229]
 [ 9.          1.57079633]
 [10.          2.21429744]
 [ 8.60232527  2.19104581]
 [ 3.60555128 -2.15879893]
 [ 8.94427191  2.03444394]
 [ 4.12310563 -1.81577499]
 [ 3.16227766  2.8198421 ]]


Задача №7. Заменить максимальный элемент массива на ноль

In [15]:
import numpy as np
arr = np.random.randint(0, 21, size=15)
print("Исходный массив:")
print(arr)
max_index = np.argmax(arr)
arr[max_index] = 0
print("\nМассив после замены максимального элемента на 0:")
print(arr)

Исходный массив:
[19 17  3 12  4 14 10  3 11 16 12 14 19  6 19]

Массив после замены максимального элемента на 0:
[ 0 17  3 12  4 14 10  3 11 16 12 14 19  6 19]


Задача №8. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве. Добавление производиться только 1 раз

In [16]:
import numpy as np
arr = np.random.randint(0, 10, size=10)
print("Исходный массив:")
print(arr)
indices = np.random.randint(0, 10, size=6)
print("\nИндексы, по которым нужно прибавить 1 (с повторами):")
print(indices)
unique_indices = np.unique(indices)
arr[unique_indices] += 1
print("\nМассив после прибавления 1 по уникальным индексам:")
print(arr)

Исходный массив:
[9 3 0 0 4 0 9 0 2 5]

Индексы, по которым нужно прибавить 1 (с повторами):
[0 9 4 6 6 0]

Массив после прибавления 1 по уникальным индексам:
[10  3  0  0  5  0 10  0  2  6]


Задача №9. Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [17]:
import numpy as np
vector = np.array([1, 2, 3, 4, 5])
print("Исходный вектор:")
print(vector)
new_vector = np.zeros(4 * len(vector) - 1, dtype=int)
new_vector[::4] = vector
print("\nНовый вектор с тремя нулями между каждым значением:")
print(new_vector)

Исходный вектор:
[1 2 3 4 5]

Новый вектор с тремя нулями между каждым значением:
[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5 0 0]


Задача №10. Найти ближайшее к заданному значению число в заданном массиве

In [18]:
import numpy as np
arr = np.random.randint(0, 100, size=10)
print("Массив:")
print(arr)
target = 50
print("\nЗаданное значение:", target)
closest_value = arr[np.abs(arr - target).argmin()]
print("\nБлижайшее значение в массиве:", closest_value)

Массив:
[37 82 35 58 16 16  7  2 98 51]

Заданное значение: 50

Ближайшее значение в массиве: 51
